language: python
python:
  - "3.6"
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment --file environment.txt
  - source activate test-environment
  - pip install codecov

script:
    cd src
    pytest --cov=src/ --cov-config src/.coveragerc

after_success:
  - codecov
