msprime_script: "/home/tcomi/projects/abwolf_abc/\
                 msprime_scripts/src/Admixture_Simulation.py"
sstar_dir: "/home/tcomi/projects/abwolf_abc/Sstar"
vcftools_bin: "/tigress/AKEY/akey_vol1/software/Vcftools/vcftools-v0.1.15/bin/vcftools"
match_pvalue_dir: "/home/tcomi/projects/abwolf_abc/abwolf_match_pvalue_simulations"

#NOTE: model and length are handled in code
msprime_base_params: "-r 216"
model: "Sriram"
length: 1e6

base_output_directory: "/tigress/tcomi/abwolf_abc"
#null is always stored in base/null
null_simulations: 11
msprime_null_params: "-n 0.0 -d 0.0 \
                      -g AF_EU_0 -g EU_AF_0 -g EU_AS_0 \
                      -g AS_EU_0 -g AF_AS_0 -g AS_AF_0 \
                      -G AF_B_0 -G B_AF_0"

admixed_simulations: 10
admixed_dir: "n1_0.1_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0"
msprime_admixed_params: "-n 0.1 -d 0.0 \
                      -g AF_EU_0 -g EU_AF_0.0005 -g EU_AS_0 \
                      -g AS_EU_0 -g AF_AS_0 -g AS_AF_0 \
                      -G AF_B_0 -G B_AF_0"
