---
paths:
    msprime_script: "/home/tcomi/projects/abwolf_abc/msprime_scripts\
                     /src/Admixture_Simulation.py"
    sstar_dir: "/home/tcomi/projects/abwolf_abc/Sstar"
    vcftools_bin: "/tigress/AKEY/akey_vol1/software/Vcftools/\
                   vcftools-v0.1.15/bin/vcftools"

    base_output: "/tigress/tcomi/abwolf_abc/{model}"
    admixed_dir: "__BASE_OUTPUT__/n1_0.1_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0"
    # copy of this file is stored in admixed_dir
    config_copy: "__ADMIXED_DIR__/config_copy.yaml"

    # null is always stored in base/null
    null_dir: "__BASE_OUTPUT__/null"

    popfile: "__BASE_OUTPUT__/base.popfile"
    bedfile: "__BASE_OUTPUT__/{directory}/TreeCalls/{seed}.bed.merged.gz"
    combined_bed: "__BASE_OUTPUT__/{directory}/TreeCalls/All.bed.gz"
    haplotype_map: "__BASE_OUTPUT__/{directory}/haplotype_to_sample.txt"
    window_calc: "__BASE_OUTPUT__/{directory}/RegionFiles/{seed}.windowcalc.gz"
    chr_list: "__BASE_OUTPUT__/{directory}/{model}.chr_list"
    options: "__BASE_OUTPUT__/{directory}/options.txt"
    raw_vcf: "__BASE_OUTPUT__/{directory}/vcfs/{seed,\\d+}.vcf.gz"
    mod_vcf: "__BASE_OUTPUT__/{directory}/vcfs/{seed}.mod.vcf.gz"
    arch_vcf: "__BASE_OUTPUT__/{directory}/vcfs/{seed}.mod.ARCHAIC.vcf.gz"
    match_counts: "__BASE_OUTPUT__/{directory}/match_pct/\
                   {seed}_match_counts.tsv"
    null_db: "__NULL_DIR__/match_pct/match_percent.db"
    pvalue_table: "__BASE_OUTPUT__/{directory}/match_pct/{seed}.tsv.gz"
    edcf_data: "__NULL_DIR__/SstarECDF_maxchrm_{chrom}.RData.gz"

msprime:
    base_params: "-r 216"
    model: "Sriram"
    length: 1000000

    null_simulations: 11
    null_params: "-n 0.0 -d 0.0 \
                          -g AF_EU_0 -g EU_AF_0 -g EU_AS_0 \
                          -g AS_EU_0 -g AF_AS_0 -g AS_AF_0 \
                          -G AF_B_0 -G B_AF_0"

    admixed_simulations: 11
    admixed_params: "-n 0.1 -d 0.0 \
                          -g AF_EU_0 -g EU_AF_0.0005 -g EU_AS_0 \
                          -g AS_EU_0 -g AF_AS_0 -g AS_AF_0 \
                          -G AF_B_0 -G B_AF_0"

s_star:
    window_size: "50000"
    window_step_size: "10000"

match_pct:
    null_name: "migration_null_10k"
    admixed_name: "0.05_pct"

    archaic:
        - "Neand1"
    modern:
        - "AFR"
        - "EUR"
    # Must be one of: `derived_in_archaic` or `derived_in_archaic_or_modern`
    informative_site_method: "derived_in_archaic"

    # Use windows from the database with informative site counts within RANGE
    # of the query windows informative site count to determine the null
    # distribution. If value is a float, it is multiplied by the count to
    # determine the range.
    informative_site_range: "0"
